config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_up', to: 'users#new', as: 'sign_up'
  post 'sign_up', to: 'users#create'

  get 'log_in', to: 'sessions#new', as: 'log_in'
  post 'log_in', to: 'sessions#create'

  delete 'log_out', to: 'sessions#destroy'
  resources :articles do
     resources :votes, only: %i[index create destroy]
     resources :bookmarks, only: %i[index create destroy]
  end
  resources :categories, only: %i[index show]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, class_name: :Article, foreign_key: :author_id
  has_many :votes
  has_many :bookmarks, foreign_key: 'user_id', dependent: :destroy
  has_many :bookmarked_articles, through: :bookmarks, source: :article

  validates :name, presence: true, length: { maximum: 40 }

  def bookmark(article)
    bookmarked_articles << article
  end

  def unbookmark(article)
    bookmarked_articles.delete(article)
  end

  def bookmarked?(article)
    bookmarked_articles.includes?(article)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, except: [:index]
  before_action :set_user, only: %i[edit show destroy update]
  def index
    @users = User.all
    @featured_article = Article.where('id = ? ', Article.featured[0])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "#{@user.name} has been created successfully."
      redirect_to root_path
    else
      flash[:alert] = 'Name field cannot be empty.'
      render :new
    end
  end

  def show; end

  def edit; end

  def destroy; end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    user.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def show_featured
    output = ''
    output << if @featured_article.present?
                "#{image_tag(@featured_article.first.image.variant(resize_to_limit: [1000, 300]))}
      <div class='feature-sub'>
      <h6>
      <strong>#{link_to(@featured_article.first.title, article_path(@featured_article.first))}</strong>
      </h6>
      <p> #{@featured_article.first.text.truncate_words(30)}</p></div>"
              else
                "<h6 class='anchor'><strong>You have no Featured articles. Get creating and voting.</strong></h6>"
              end
    output.html_safe
  end

  def show_others
    output = ''
    return unless Article.count.positive?

    Article.others.ordered_by_most_recent.each do |article|
      next unless article.image.attached?

      output << "<div class='col-3'>
        <div class='other-article'>
          #{link_to(image_tag(article.image.variant(resize_to_limit: [600, 400])), article_path(article))}
          <p>
            #{article.text.truncate_words(5)}
          </p>
          <h5 class=''>#{link_to(article.category.name,
                                 category_path(article.category.id))} </h5>
        </div>
      </div>"
    end
    output.html_safe
  end
end

app/views/users/_form.html.erb
<div class='row m-auto py-5'>
  <div class='col-3'></div>
  <div class='col-6'>
    <h2 class='text-white'>Sign Up</h2>
    <%= form_with model: @user, url: sign_up_path do |f| %>
    <%= show_errors(@user) %>
    <div class='input-group'>
      <span class='input-group-text'>
        <i class="fas fa-user"></i>
      </span>
      <%= f.text_field :name, placeholder: 'Enter your name to sign Up', class: 'form-control' %>
    </div>

    <div class='mt-3'>
      <%= f.submit 'Sign Up', class: 'btn btn-primary' %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<section class='row g-0'>
  <div class='featured col-12 d-flex justify-content-center'>
    <%= show_featured %>
  </div>
  <article class='d-flex bg-white'>
    <%= show_others %>
  </article>
</section>

app/views/users/new.html.erb
<%= render 'form' %>