config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_up', to: 'users#new', as: 'sign_up'
  post 'sign_up', to: 'users#create'

  get 'log_in', to: 'sessions#new', as: 'log_in'
  post 'log_in', to: 'sessions#create'

  delete 'log_out', to: 'sessions#destroy'
  resources :articles do
     resources :votes, only: %i[index create destroy]
     resources :bookmarks, only: %i[index create destroy]
  end
  resources :categories, only: %i[index show]

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories, dependent: :destroy
  has_many :articles

  enum priority: %i[high medium low]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    name = 'TV'
    @category = Article.category(name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def show_category
    output = ''

    output.html_safe
  end
end

app/views/categories/index.html.erb
<article>
  <div class='card'>
    <% @categories.each do |cat| %>
    <div class="row g-0">
      <div class='col-3'>
        <%= link_to cat.name, category_path(cat) %>
      </div>
      <div class='col-3'>
        <div class='card-body'>
          <h5 class='card-title'></h5>
          <p class='card-text'>

          </p>
          <em class="badge bg-primary mx-3"></em>
          <h6 class="card-text mt-2"><strong>Author: </strong>
          </h6>
        </div>
      </div>
      <% end%>
    </div>
  </div>
  </div>
  <article>

app/views/categories/show.html.erb
<div class='category text-secondary'>
  <ul class='double mr-0'>
    <% @article = Article.where('category_id = ?', params[:id])%>
    <% @article.each do |art_cat| %>
    <li>
      <div class='d-flex flex-row mb-3 bg-white'>
        <%= image_tag(art_cat.image.variant(resize_to_limit: [500, 500]))%>
        <div class='d-flex flex-column mx-2'>
          <strong class='article-header'><%=link_to(art_cat.title.truncate_words(15), article_path(art_cat.id)) %></strong>
          <p><%= art_cat.text.truncate_words(5) %></p>
          <em><%= art_cat.author.name %><em>
              <div class='mt-3'>
                <%= show_vote_btn(art_cat)%>
                <em class="badge bg-primary mx-3"><%= art_cat.votes.count.to_s + ' Vote(s)' %></em>
              </div>
        </div>
      </div>
    </li>
    <% end %>
  </ul>
</div>